// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.4
// source: rating_service.proto

package rating

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllRatingsHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllRatingsHostRequest) Reset() {
	*x = GetAllRatingsHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRatingsHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRatingsHostRequest) ProtoMessage() {}

func (x *GetAllRatingsHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRatingsHostRequest.ProtoReflect.Descriptor instead.
func (*GetAllRatingsHostRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{0}
}

type GetAllRatingsHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RatingsHost []*RatingHost `protobuf:"bytes,1,rep,name=ratingsHost,proto3" json:"ratingsHost,omitempty"`
}

func (x *GetAllRatingsHostResponse) Reset() {
	*x = GetAllRatingsHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRatingsHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRatingsHostResponse) ProtoMessage() {}

func (x *GetAllRatingsHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRatingsHostResponse.ProtoReflect.Descriptor instead.
func (*GetAllRatingsHostResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllRatingsHostResponse) GetRatingsHost() []*RatingHost {
	if x != nil {
		return x.RatingsHost
	}
	return nil
}

type RatingHost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HostId  string `protobuf:"bytes,2,opt,name=hostId,proto3" json:"hostId,omitempty"`
	GuestId string `protobuf:"bytes,3,opt,name=guestId,proto3" json:"guestId,omitempty"`
	Rate    int32  `protobuf:"varint,4,opt,name=rate,proto3" json:"rate,omitempty"`
	Date    string `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *RatingHost) Reset() {
	*x = RatingHost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RatingHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingHost) ProtoMessage() {}

func (x *RatingHost) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingHost.ProtoReflect.Descriptor instead.
func (*RatingHost) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{2}
}

func (x *RatingHost) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RatingHost) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RatingHost) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *RatingHost) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *RatingHost) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type NewRatingHost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId  string `protobuf:"bytes,1,opt,name=hostId,proto3" json:"hostId,omitempty"`
	GuestId string `protobuf:"bytes,2,opt,name=guestId,proto3" json:"guestId,omitempty"`
	Rate    int32  `protobuf:"varint,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Date    string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *NewRatingHost) Reset() {
	*x = NewRatingHost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewRatingHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRatingHost) ProtoMessage() {}

func (x *NewRatingHost) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRatingHost.ProtoReflect.Descriptor instead.
func (*NewRatingHost) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{3}
}

func (x *NewRatingHost) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *NewRatingHost) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *NewRatingHost) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *NewRatingHost) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type RatingAccommodation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccommodationId string `protobuf:"bytes,2,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
	GuestId         string `protobuf:"bytes,3,opt,name=guestId,proto3" json:"guestId,omitempty"`
	Rate            int32  `protobuf:"varint,4,opt,name=rate,proto3" json:"rate,omitempty"`
	Date            string `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *RatingAccommodation) Reset() {
	*x = RatingAccommodation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RatingAccommodation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingAccommodation) ProtoMessage() {}

func (x *RatingAccommodation) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingAccommodation.ProtoReflect.Descriptor instead.
func (*RatingAccommodation) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{4}
}

func (x *RatingAccommodation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RatingAccommodation) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

func (x *RatingAccommodation) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *RatingAccommodation) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *RatingAccommodation) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type NewRatingAccommodation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccommodationId string `protobuf:"bytes,1,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
	GuestId         string `protobuf:"bytes,2,opt,name=guestId,proto3" json:"guestId,omitempty"`
	Rate            int32  `protobuf:"varint,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Date            string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *NewRatingAccommodation) Reset() {
	*x = NewRatingAccommodation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewRatingAccommodation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRatingAccommodation) ProtoMessage() {}

func (x *NewRatingAccommodation) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRatingAccommodation.ProtoReflect.Descriptor instead.
func (*NewRatingAccommodation) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{5}
}

func (x *NewRatingAccommodation) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

func (x *NewRatingAccommodation) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *NewRatingAccommodation) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *NewRatingAccommodation) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type CreateRatingForHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RatingHost *NewRatingHost `protobuf:"bytes,1,opt,name=ratingHost,proto3" json:"ratingHost,omitempty"`
}

func (x *CreateRatingForHostRequest) Reset() {
	*x = CreateRatingForHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRatingForHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingForHostRequest) ProtoMessage() {}

func (x *CreateRatingForHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingForHostRequest.ProtoReflect.Descriptor instead.
func (*CreateRatingForHostRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRatingForHostRequest) GetRatingHost() *NewRatingHost {
	if x != nil {
		return x.RatingHost
	}
	return nil
}

type CreateRatingForHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RatingHost *RatingHost `protobuf:"bytes,1,opt,name=ratingHost,proto3" json:"ratingHost,omitempty"`
}

func (x *CreateRatingForHostResponse) Reset() {
	*x = CreateRatingForHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRatingForHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingForHostResponse) ProtoMessage() {}

func (x *CreateRatingForHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingForHostResponse.ProtoReflect.Descriptor instead.
func (*CreateRatingForHostResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRatingForHostResponse) GetRatingHost() *RatingHost {
	if x != nil {
		return x.RatingHost
	}
	return nil
}

type DeleteRatingForHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRatingForHostRequest) Reset() {
	*x = DeleteRatingForHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRatingForHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRatingForHostRequest) ProtoMessage() {}

func (x *DeleteRatingForHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRatingForHostRequest.ProtoReflect.Descriptor instead.
func (*DeleteRatingForHostRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRatingForHostRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRatingForHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RatingHost *RatingHost `protobuf:"bytes,1,opt,name=ratingHost,proto3" json:"ratingHost,omitempty"`
}

func (x *DeleteRatingForHostResponse) Reset() {
	*x = DeleteRatingForHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRatingForHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRatingForHostResponse) ProtoMessage() {}

func (x *DeleteRatingForHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRatingForHostResponse.ProtoReflect.Descriptor instead.
func (*DeleteRatingForHostResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRatingForHostResponse) GetRatingHost() *RatingHost {
	if x != nil {
		return x.RatingHost
	}
	return nil
}

type UpdateRatingForHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RatingHost *RatingHost `protobuf:"bytes,1,opt,name=ratingHost,proto3" json:"ratingHost,omitempty"`
}

func (x *UpdateRatingForHostRequest) Reset() {
	*x = UpdateRatingForHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRatingForHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRatingForHostRequest) ProtoMessage() {}

func (x *UpdateRatingForHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRatingForHostRequest.ProtoReflect.Descriptor instead.
func (*UpdateRatingForHostRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRatingForHostRequest) GetRatingHost() *RatingHost {
	if x != nil {
		return x.RatingHost
	}
	return nil
}

type UpdateRatingForHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RatingHost *RatingHost `protobuf:"bytes,1,opt,name=ratingHost,proto3" json:"ratingHost,omitempty"`
}

func (x *UpdateRatingForHostResponse) Reset() {
	*x = UpdateRatingForHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRatingForHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRatingForHostResponse) ProtoMessage() {}

func (x *UpdateRatingForHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRatingForHostResponse.ProtoReflect.Descriptor instead.
func (*UpdateRatingForHostResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRatingForHostResponse) GetRatingHost() *RatingHost {
	if x != nil {
		return x.RatingHost
	}
	return nil
}

type CreateRatingForAccommodationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RatingAccommodation *NewRatingAccommodation `protobuf:"bytes,1,opt,name=ratingAccommodation,proto3" json:"ratingAccommodation,omitempty"`
}

func (x *CreateRatingForAccommodationRequest) Reset() {
	*x = CreateRatingForAccommodationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRatingForAccommodationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingForAccommodationRequest) ProtoMessage() {}

func (x *CreateRatingForAccommodationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingForAccommodationRequest.ProtoReflect.Descriptor instead.
func (*CreateRatingForAccommodationRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{12}
}

func (x *CreateRatingForAccommodationRequest) GetRatingAccommodation() *NewRatingAccommodation {
	if x != nil {
		return x.RatingAccommodation
	}
	return nil
}

type CreateRatingForAccommodationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RatingAccommodation *RatingAccommodation `protobuf:"bytes,1,opt,name=ratingAccommodation,proto3" json:"ratingAccommodation,omitempty"`
}

func (x *CreateRatingForAccommodationResponse) Reset() {
	*x = CreateRatingForAccommodationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRatingForAccommodationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingForAccommodationResponse) ProtoMessage() {}

func (x *CreateRatingForAccommodationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingForAccommodationResponse.ProtoReflect.Descriptor instead.
func (*CreateRatingForAccommodationResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRatingForAccommodationResponse) GetRatingAccommodation() *RatingAccommodation {
	if x != nil {
		return x.RatingAccommodation
	}
	return nil
}

type GetAvgRatingForHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId string `protobuf:"bytes,1,opt,name=hostId,proto3" json:"hostId,omitempty"`
}

func (x *GetAvgRatingForHostRequest) Reset() {
	*x = GetAvgRatingForHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvgRatingForHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvgRatingForHostRequest) ProtoMessage() {}

func (x *GetAvgRatingForHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvgRatingForHostRequest.ProtoReflect.Descriptor instead.
func (*GetAvgRatingForHostRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetAvgRatingForHostRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type GetAvgRatingForHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvgRating float32 `protobuf:"fixed32,1,opt,name=avgRating,proto3" json:"avgRating,omitempty"`
}

func (x *GetAvgRatingForHostResponse) Reset() {
	*x = GetAvgRatingForHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvgRatingForHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvgRatingForHostResponse) ProtoMessage() {}

func (x *GetAvgRatingForHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvgRatingForHostResponse.ProtoReflect.Descriptor instead.
func (*GetAvgRatingForHostResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetAvgRatingForHostResponse) GetAvgRating() float32 {
	if x != nil {
		return x.AvgRating
	}
	return 0
}

var File_rating_service_proto protoreflect.FileDescriptor

var file_rating_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x0b,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x22, 0x76, 0x0a, 0x0a, 0x52,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x22, 0x69, 0x0a, 0x0d, 0x4e, 0x65, 0x77, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x48, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x91,
	0x01, 0x0a, 0x13, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x67, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x67, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x16, 0x4e, 0x65, 0x77, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a,
	0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x53, 0x0a, 0x1a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0a, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x65, 0x77, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x0a, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x22, 0x51,
	0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f,
	0x72, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a,
	0x0a, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x0a, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73,
	0x74, 0x22, 0x2c, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x51, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46,
	0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32,
	0x0a, 0x0a, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x0a, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f,
	0x73, 0x74, 0x22, 0x50, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x32, 0x0a, 0x0a, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x0a, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x48, 0x6f, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x0a, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x22, 0x77, 0x0a, 0x23, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x50,
	0x0a, 0x13, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x65, 0x77, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x41, 0x63,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x13, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x75, 0x0a, 0x24, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x46, 0x6f, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x13, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x13, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x34, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x76,
	0x67, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x3b, 0x0a,
	0x1b, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72,
	0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x76, 0x67, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x61, 0x76, 0x67, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x32, 0xd9, 0x06, 0x0a, 0x0d, 0x52,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6e, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x6f, 0x73,
	0x74, 0x12, 0x20, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c,
	0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x88, 0x01, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72,
	0x48, 0x6f, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f,
	0x72, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x22, 0x22, 0x14, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x3a, 0x0a, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x12, 0xb5, 0x01, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f,
	0x72, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x41, 0x63,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x3a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x34, 0x22, 0x1d, 0x2f, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x41, 0x63, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x13, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x81, 0x01, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72,
	0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x19, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x12, 0x88, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x22, 0x14, 0x2f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x48, 0x6f,
	0x73, 0x74, 0x3a, 0x0a, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x85,
	0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46,
	0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x12, 0x1d, 0x2f, 0x67, 0x65, 0x74, 0x41, 0x76, 0x67,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x2f, 0x7b, 0x68,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x7d, 0x42, 0x0f, 0x5a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rating_service_proto_rawDescOnce sync.Once
	file_rating_service_proto_rawDescData = file_rating_service_proto_rawDesc
)

func file_rating_service_proto_rawDescGZIP() []byte {
	file_rating_service_proto_rawDescOnce.Do(func() {
		file_rating_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rating_service_proto_rawDescData)
	})
	return file_rating_service_proto_rawDescData
}

var file_rating_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_rating_service_proto_goTypes = []interface{}{
	(*GetAllRatingsHostRequest)(nil),             // 0: rating.GetAllRatingsHostRequest
	(*GetAllRatingsHostResponse)(nil),            // 1: rating.GetAllRatingsHostResponse
	(*RatingHost)(nil),                           // 2: rating.RatingHost
	(*NewRatingHost)(nil),                        // 3: rating.NewRatingHost
	(*RatingAccommodation)(nil),                  // 4: rating.RatingAccommodation
	(*NewRatingAccommodation)(nil),               // 5: rating.NewRatingAccommodation
	(*CreateRatingForHostRequest)(nil),           // 6: rating.CreateRatingForHostRequest
	(*CreateRatingForHostResponse)(nil),          // 7: rating.CreateRatingForHostResponse
	(*DeleteRatingForHostRequest)(nil),           // 8: rating.DeleteRatingForHostRequest
	(*DeleteRatingForHostResponse)(nil),          // 9: rating.DeleteRatingForHostResponse
	(*UpdateRatingForHostRequest)(nil),           // 10: rating.UpdateRatingForHostRequest
	(*UpdateRatingForHostResponse)(nil),          // 11: rating.UpdateRatingForHostResponse
	(*CreateRatingForAccommodationRequest)(nil),  // 12: rating.CreateRatingForAccommodationRequest
	(*CreateRatingForAccommodationResponse)(nil), // 13: rating.CreateRatingForAccommodationResponse
	(*GetAvgRatingForHostRequest)(nil),           // 14: rating.GetAvgRatingForHostRequest
	(*GetAvgRatingForHostResponse)(nil),          // 15: rating.GetAvgRatingForHostResponse
}
var file_rating_service_proto_depIdxs = []int32{
	2,  // 0: rating.GetAllRatingsHostResponse.ratingsHost:type_name -> rating.RatingHost
	3,  // 1: rating.CreateRatingForHostRequest.ratingHost:type_name -> rating.NewRatingHost
	2,  // 2: rating.CreateRatingForHostResponse.ratingHost:type_name -> rating.RatingHost
	2,  // 3: rating.DeleteRatingForHostResponse.ratingHost:type_name -> rating.RatingHost
	2,  // 4: rating.UpdateRatingForHostRequest.ratingHost:type_name -> rating.RatingHost
	2,  // 5: rating.UpdateRatingForHostResponse.ratingHost:type_name -> rating.RatingHost
	5,  // 6: rating.CreateRatingForAccommodationRequest.ratingAccommodation:type_name -> rating.NewRatingAccommodation
	4,  // 7: rating.CreateRatingForAccommodationResponse.ratingAccommodation:type_name -> rating.RatingAccommodation
	0,  // 8: rating.RatingService.GetAllRatingsHost:input_type -> rating.GetAllRatingsHostRequest
	6,  // 9: rating.RatingService.CreateRatingForHost:input_type -> rating.CreateRatingForHostRequest
	12, // 10: rating.RatingService.CreateRatingForAccommodation:input_type -> rating.CreateRatingForAccommodationRequest
	8,  // 11: rating.RatingService.DeleteRatingForHost:input_type -> rating.DeleteRatingForHostRequest
	10, // 12: rating.RatingService.UpdateRatingForHost:input_type -> rating.UpdateRatingForHostRequest
	14, // 13: rating.RatingService.GetAvgRatingForHost:input_type -> rating.GetAvgRatingForHostRequest
	1,  // 14: rating.RatingService.GetAllRatingsHost:output_type -> rating.GetAllRatingsHostResponse
	7,  // 15: rating.RatingService.CreateRatingForHost:output_type -> rating.CreateRatingForHostResponse
	13, // 16: rating.RatingService.CreateRatingForAccommodation:output_type -> rating.CreateRatingForAccommodationResponse
	9,  // 17: rating.RatingService.DeleteRatingForHost:output_type -> rating.DeleteRatingForHostResponse
	11, // 18: rating.RatingService.UpdateRatingForHost:output_type -> rating.UpdateRatingForHostResponse
	15, // 19: rating.RatingService.GetAvgRatingForHost:output_type -> rating.GetAvgRatingForHostResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_rating_service_proto_init() }
func file_rating_service_proto_init() {
	if File_rating_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rating_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRatingsHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRatingsHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RatingHost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewRatingHost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RatingAccommodation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewRatingAccommodation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRatingForHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRatingForHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRatingForHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRatingForHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRatingForHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRatingForHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRatingForAccommodationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRatingForAccommodationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvgRatingForHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvgRatingForHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rating_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rating_service_proto_goTypes,
		DependencyIndexes: file_rating_service_proto_depIdxs,
		MessageInfos:      file_rating_service_proto_msgTypes,
	}.Build()
	File_rating_service_proto = out.File
	file_rating_service_proto_rawDesc = nil
	file_rating_service_proto_goTypes = nil
	file_rating_service_proto_depIdxs = nil
}
