// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.4
// source: rating_service.proto

package rating

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllRatingsHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllRatingsHostRequest) Reset() {
	*x = GetAllRatingsHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRatingsHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRatingsHostRequest) ProtoMessage() {}

func (x *GetAllRatingsHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRatingsHostRequest.ProtoReflect.Descriptor instead.
func (*GetAllRatingsHostRequest) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{0}
}

type GetAllRatingsHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RatingsHost []*RatingHost `protobuf:"bytes,1,rep,name=ratingsHost,proto3" json:"ratingsHost,omitempty"`
}

func (x *GetAllRatingsHostResponse) Reset() {
	*x = GetAllRatingsHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRatingsHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRatingsHostResponse) ProtoMessage() {}

func (x *GetAllRatingsHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRatingsHostResponse.ProtoReflect.Descriptor instead.
func (*GetAllRatingsHostResponse) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllRatingsHostResponse) GetRatingsHost() []*RatingHost {
	if x != nil {
		return x.RatingsHost
	}
	return nil
}

type RatingHost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HostId  string `protobuf:"bytes,2,opt,name=hostId,proto3" json:"hostId,omitempty"`
	GuestId string `protobuf:"bytes,3,opt,name=guestId,proto3" json:"guestId,omitempty"`
	Rate    int32  `protobuf:"varint,4,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *RatingHost) Reset() {
	*x = RatingHost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RatingHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingHost) ProtoMessage() {}

func (x *RatingHost) ProtoReflect() protoreflect.Message {
	mi := &file_rating_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingHost.ProtoReflect.Descriptor instead.
func (*RatingHost) Descriptor() ([]byte, []int) {
	return file_rating_service_proto_rawDescGZIP(), []int{2}
}

func (x *RatingHost) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RatingHost) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RatingHost) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *RatingHost) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

var File_rating_service_proto protoreflect.FileDescriptor

var file_rating_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x0b,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x22, 0x62, 0x0a, 0x0a, 0x52,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x32,
	0x7f, 0x0a, 0x0d, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x6e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0e, 0x12, 0x0c, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x6f, 0x73, 0x74,
	0x42, 0x0f, 0x5a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rating_service_proto_rawDescOnce sync.Once
	file_rating_service_proto_rawDescData = file_rating_service_proto_rawDesc
)

func file_rating_service_proto_rawDescGZIP() []byte {
	file_rating_service_proto_rawDescOnce.Do(func() {
		file_rating_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rating_service_proto_rawDescData)
	})
	return file_rating_service_proto_rawDescData
}

var file_rating_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rating_service_proto_goTypes = []interface{}{
	(*GetAllRatingsHostRequest)(nil),  // 0: rating.GetAllRatingsHostRequest
	(*GetAllRatingsHostResponse)(nil), // 1: rating.GetAllRatingsHostResponse
	(*RatingHost)(nil),                // 2: rating.RatingHost
}
var file_rating_service_proto_depIdxs = []int32{
	2, // 0: rating.GetAllRatingsHostResponse.ratingsHost:type_name -> rating.RatingHost
	0, // 1: rating.RatingService.GetAllRatingsHost:input_type -> rating.GetAllRatingsHostRequest
	1, // 2: rating.RatingService.GetAllRatingsHost:output_type -> rating.GetAllRatingsHostResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rating_service_proto_init() }
func file_rating_service_proto_init() {
	if File_rating_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rating_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRatingsHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRatingsHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RatingHost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rating_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rating_service_proto_goTypes,
		DependencyIndexes: file_rating_service_proto_depIdxs,
		MessageInfos:      file_rating_service_proto_msgTypes,
	}.Build()
	File_rating_service_proto = out.File
	file_rating_service_proto_rawDesc = nil
	file_rating_service_proto_goTypes = nil
	file_rating_service_proto_depIdxs = nil
}
